name: Bug Report
description: Create a report to help us improve
labels: unconfirmed bug
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to submit an issue! These improve the library and makes the overall experience much better.
        
        
        If you'd like real-time assistance, consider joining our Discord at https://discord.gg/TYDZeruQ7N instead.
  - type: textarea
    attributes:
      label: Describe the bug
      description: A quick but concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproducible Code
      description: A simplified but complete version of the code you used when the bug occurred. This is automatically converted into Swift code, so there's no need for backticks.
      render: swift
    validations:
      required: true
  - type: textarea
    attributes:
      label: Printed Error
      description: The entire error message or "None" if no error message was displayed.
      render: txt
    validations:
      required: true
  - type: input
    attributes:
      label: Library Version
      description: | 
        The version should be displayed as one of the following:
        1. The exact version (0.0.15-alpha)
        2. The commit hash (af3c2d6)
        3. The main branch (simply put "main branch"). This also means you're using the most up-to-date version of *main* at the time of this issue.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Required Checklist
      description: A checklist to ensure the issue can be resolved without unnecessary delay.
      options:
        - label: This issue is not a duplicate.
          required: true
        - label: I have the necessary intents enabled.
          required: true
        - label: My token is not visible.
          required: true
  - type: textarea
    attributes:
      label: Additional Comments
      description: Any additional comments can be posted here.
